using HospitalManagementSystem.Models;
using HospitalManagementSystem.Services;

PatientService patientService = new();
DoctorService doctorService = new();
AppointmentService appointmentService = new();

while (true)
{
    Console.WriteLine("\n=======================================");
    Console.WriteLine("      HOSPITAL MANAGEMENT SYSTEM");
    Console.WriteLine("=======================================");
    Console.WriteLine("1. Add Patient");
    Console.WriteLine("2. View Patients");
    Console.WriteLine("3. Add Doctor");
    Console.WriteLine("4. View Doctors");
    Console.WriteLine("5. Book Appointment");
    Console.WriteLine("6. View Appointments");
    Console.WriteLine("7. Delete Patient");
    Console.WriteLine("8. Delete Doctor");
    Console.WriteLine("9. Delete Appointment");
    Console.WriteLine("10. Exit");
    Console.WriteLine("=======================================");

    Console.Write("\nSelect an option: ");

    if (!int.TryParse(Console.ReadLine(), out int choice))
    {
        Console.WriteLine("Invalid input. Please enter a number.");
        continue;
    }

    switch (choice)
    {
        // ==========================================
        // ADD PATIENT
        // ==========================================
        case 1:
        {
            Console.WriteLine("\n========== ADD PATIENT ==========");

            Console.Write("Name: ");
            string patientName = Console.ReadLine() ?? "";

            if (string.IsNullOrWhiteSpace(patientName))
            {
                Console.WriteLine("Patient name cannot be empty.");
                break;
            }

            Console.Write("Age: ");

            if (!int.TryParse(Console.ReadLine(), out int age) || age <= 0)
            {
                Console.WriteLine("Invalid age.");
                break;
            }

            Console.Write("Gender: ");
            string gender = Console.ReadLine() ?? "";

            if (string.IsNullOrWhiteSpace(gender))
            {
                Console.WriteLine("Gender cannot be empty.");
                break;
            }

            Console.Write("Phone Number: ");
            string phone = Console.ReadLine() ?? "";

            if (string.IsNullOrWhiteSpace(phone))
            {
                Console.WriteLine("Phone number cannot be empty.");
                break;
            }

            Console.Write("Address: ");
            string address = Console.ReadLine() ?? "";

            if (string.IsNullOrWhiteSpace(address))
            {
                Console.WriteLine("Address cannot be empty.");
                break;
            }

            // ID is automatically generated by PatientService
            int patientId = patientService.GetNextPatientId();

            Patient patient = new Patient(
                patientId,
                patientName,
                age,
                gender,
                phone,
                address
            );

            patientService.AddPatient(patient);

            Console.WriteLine($"Patient ID generated: {patient.Id}");

            break;
        }

        // ==========================================
        // VIEW PATIENTS
        // ==========================================
        case 2:
        {
            Console.WriteLine("\n========== PATIENT LIST ==========");

            patientService.ViewPatients();

            break;
        }

        // ==========================================
        // ADD DOCTOR
        // ==========================================
        case 3:
        {
            Console.WriteLine("\n========== ADD DOCTOR ==========");

            Console.Write("Doctor Name: ");
            string doctorName = Console.ReadLine() ?? "";

            if (string.IsNullOrWhiteSpace(doctorName))
            {
                Console.WriteLine("Doctor name cannot be empty.");
                break;
            }

            Console.Write("Specialty: ");
            string specialty = Console.ReadLine() ?? "";

            if (string.IsNullOrWhiteSpace(specialty))
            {
                Console.WriteLine("Specialty cannot be empty.");
                break;
            }

            Console.Write("Phone Number: ");
            string doctorPhone = Console.ReadLine() ?? "";

            if (string.IsNullOrWhiteSpace(doctorPhone))
            {
                Console.WriteLine("Phone number cannot be empty.");
                break;
            }

            // ID is automatically generated by DoctorService
            int doctorId = doctorService.GetNextDoctorId();

            Doctor doctor = new Doctor(
                doctorId,
                doctorName,
                specialty,
                doctorPhone
            );

            doctorService.AddDoctor(doctor);

            Console.WriteLine($"Doctor ID generated: {doctor.Id}");

            break;
        }

        // ==========================================
        // VIEW DOCTORS
        // ==========================================
        case 4:
        {
            Console.WriteLine("\n========== DOCTOR LIST ==========");

            doctorService.ViewDoctors();

            break;
        }

        // ==========================================
        // BOOK APPOINTMENT
        // ==========================================
        case 5:
        {
            Console.WriteLine("\n========== BOOK APPOINTMENT ==========");

            Console.Write("Patient ID: ");

            if (!int.TryParse(
                    Console.ReadLine(),
                    out int patientId))
            {
                Console.WriteLine("Invalid patient ID.");
                break;
            }

            // Check that the patient exists
            Patient? patient = patientService.GetPatientById(patientId);

            if (patient == null)
            {
                Console.WriteLine("Patient not found.");
                Console.WriteLine(
                    "Please register the patient before booking an appointment."
                );
                break;
            }

            Console.Write("Doctor ID: ");

            if (!int.TryParse(
                    Console.ReadLine(),
                    out int doctorId))
            {
                Console.WriteLine("Invalid doctor ID.");
                break;
            }

            // Check that the doctor exists
            Doctor? doctor = doctorService.GetDoctorById(doctorId);

            if (doctor == null)
            {
                Console.WriteLine("Doctor not found.");
                Console.WriteLine(
                    "Please register the doctor before booking an appointment."
                );
                break;
            }

            Console.Write("Appointment Date (yyyy-mm-dd): ");

            if (!DateTime.TryParse(
                    Console.ReadLine(),
                    out DateTime appointmentDate))
            {
                Console.WriteLine("Invalid appointment date.");
                break;
            }

            Console.Write("Reason: ");
            string reason = Console.ReadLine() ?? "";

            if (string.IsNullOrWhiteSpace(reason))
            {
                Console.WriteLine("Appointment reason cannot be empty.");
                break;
            }

            // ID is automatically generated by AppointmentService
            int appointmentId =
                appointmentService.GetNextAppointmentId();

            Appointment appointment = new Appointment(
                appointmentId,
                patientId,
                doctorId,
                appointmentDate,
                reason
            );

            appointmentService.AddAppointment(appointment);

            Console.WriteLine(
                $"Appointment ID generated: {appointment.Id}"
            );

            break;
        }

        // ==========================================
        // VIEW APPOINTMENTS
        // ==========================================
        case 6:
        {
            Console.WriteLine("\n========== APPOINTMENT LIST ==========");

            appointmentService.ViewAppointments();

            break;
        }

        // ==========================================
        // DELETE PATIENT
        // ==========================================
        case 7:
        {
            Console.WriteLine("\n========== DELETE PATIENT ==========");

            Console.Write("Enter patient ID: ");

            if (!int.TryParse(
                    Console.ReadLine(),
                    out int patientId))
            {
                Console.WriteLine("Invalid patient ID.");
                break;
            }

            patientService.DeletePatient(patientId);

            break;
        }

        // ==========================================
        // DELETE DOCTOR
        // ==========================================
        case 8:
        {
            Console.WriteLine("\n========== DELETE DOCTOR ==========");

            Console.Write("Enter doctor ID: ");

            if (!int.TryParse(
                    Console.ReadLine(),
                    out int doctorId))
            {
                Console.WriteLine("Invalid doctor ID.");
                break;
            }

            doctorService.DeleteDoctor(doctorId);

            break;
        }

        // ==========================================
        // DELETE APPOINTMENT
        // ==========================================
        case 9:
        {
            Console.WriteLine("\n========== DELETE APPOINTMENT ==========");

            Console.Write("Enter appointment ID: ");

            if (!int.TryParse(
                    Console.ReadLine(),
                    out int appointmentId))
            {
                Console.WriteLine("Invalid appointment ID.");
                break;
            }

            appointmentService.DeleteAppointment(appointmentId);

            break;
        }

        // ==========================================
        // EXIT
        // ==========================================
        case 10:
        {
            Console.WriteLine("\nThank you for using the");
            Console.WriteLine("Hospital Management System.");
            Console.WriteLine("Goodbye!");

            return;
        }

        default:
        {
            Console.WriteLine(
                "Invalid option. Please select 1-10."
            );

            break;
        }
    }
}